---
title: "Homework 6"
author: "Jeanette Shekelle"
date: "11/27/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
```


### Introduction:

The purpose of this document is to practice fitting linear models for P8105 Homework 6. 


## Problem 1


#### Reading in the data:

```{r}
homicide_data = read_csv(file = "./data/homicide_data.csv")
```


Cleaning the data:


```{r}
homicide_data_clean = 
  homicide_data %>% 
  janitor::clean_names() %>% 
  mutate(city_state = paste(city, state, sep = ', '),
         solved = as.factor(ifelse(disposition == 'Closed by arrest', 'solved', 'unsolved'))) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) %>% 
  mutate(victim_race = as.factor(ifelse(victim_race == 'White', 'white', 'non-white' )),
         victim_age = as.numeric(victim_age),
         victim_sex = as.factor(victim_sex),
         victim_race = fct_relevel(victim_race, "white"))
```



Fitting logistic regression using glm:

```{r}
fit_logistic = 
  homicide_data_clean%>% 
  filter(city_state == "Baltimore, MD") %>%
  glm(solved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         low_OR = exp(estimate * 1.96 - std.error),
         high_OR = exp(estimate * 1.96 + std.error)) %>%
  select(OR, low_OR, high_OR, p.value) %>% 
  knitr::kable(digits = 3)
```


## Problem 2

Loading birthweight data:

```{r}
birthweight_data = read_csv(file = "./data/birthweight.csv")
```


Cleaning the data for regression analysis:

```{r}
birthweight_data_clean = 
  birthweight_data %>% 
  janitor::clean_names() %>% 
  mutate(malform = as.factor(malform),
         babysex = as.factor(babysex),
         mrace = as.factor(mrace),
         pnumlbw = as.numeric(pnumlbw),
         pnumsga = as.numeric(pnumsga))
```

